Add donor role, nickname, and avatar integration with RW
williamjacksn/wormgas pull request #84
Opened 2021-05-28 20:47 UTC by rmcauley

Draft status for now, please leave feedback and teach me how to test locally before pushing. :)

2021-06-02 20:43 UTC, williamjacksn requested changes
First time using GitHub's pull request review tools. Hopefully this works.

2021-06-02 20:43 UTC, williamjacksn commented on wormgas/cogs/rainwave.py
> +    async def sync_donors(self):
`discord.errors.ClientException: Callback for sync_donors command is missing "ctx" parameter.`

```suggestion
    async def sync_donors(self, ctx: cmds.Context):
```

2021-06-02 20:43 UTC, williamjacksn commented on wormgas/cogs/rainwave.py
> +            donor_role = self.config.get("rainwave:donor_role_id")
```suggestion
        if self.bot.config.get("rainwave:donor_role_id"):
            donor_role = self.bot.config.get("rainwave:donor_role_id")
```

2021-06-02 20:43 UTC, williamjacksn commented on wormgas/cogs/rainwave.py
> +        if not self.config.get("rainwave:donor_role_id"):
```suggestion
        if not self.bot.config.get("rainwave:donor_role_id"):
```

2021-06-02 20:43 UTC, williamjacksn commented on wormgas/cogs/rainwave.py
> +        donor_role = self.config.get("rainwave:donor_role_id")
```suggestion
        donor_role = self.bot.config.get("rainwave:donor_role_id")
```

2021-06-02 20:43 UTC, williamjacksn commented on wormgas/cogs/rainwave.py
> +        if self.config.get("rainwave:sync_donor_role_on_ready"):
```suggestion
        if self.bot.config.get("rainwave:sync_donor_role_on_ready"):
```

2021-06-02 20:43 UTC, williamjacksn commented on wormgas/cogs/rainwave.py
> +                if donor_role in member.roles:
```suggestion
            role = guild.get_role(donor_role)
            for member in guild.members:
                if role in member.roles:
```

2021-06-03 13:05 UTC, rmcauley commented
All fixes applied!

2021-06-03 14:04 UTC, merged